# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='pub_dat',
            new_name='pub_date',
        ),
    ]
